version: "3.8"

services:
  cyberstorm-nextjs:
    container_name: cyberstorm-nextjs
    command: /bin/sh -c "tail -f /dev/null"
    build:
      context: "./"
      dockerfile: "apps/cyberstorm-nextjs/Dockerfile.development"
      secrets:
        - "npmrc"
    image: thunderstore/thunderstore-ui.cyberstorm-nextjs-development:${IMAGE_TAG:-dev}
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./apps/cyberstorm-nextjs:/app/apps/cyberstorm-nextjs
      - ./packages:/app/packages
    networks:
        - thunderstore_default
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true

  nextjs-nginx-proxy:
    image: nginx
    container_name: nextjs-nginx-proxy
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/www:/var/www:ro
      - ./nginx/conf.d/nextjsdefault.conf:/etc/nginx/conf.d/default.conf:ro
      # - ./ssl:/etc/nginx/ssl:ro
      # - ./snippets:/etc/nginx/snippets:ro
      # - ./protect:/etc/nginx/protect:ro
    hostname: thunderstore.temp
    networks:
        - thunderstore_default


secrets:
  npmrc:
    file: "./build-secrets/.npmrc"

volumes:
  nginx-data:

networks:
  thunderstore_default:
    name: thunderstore_default
    external: true
