# Workflow for detecting visual changes in Storybook components.
name: 'Chromatic'
on: push

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        projects: [
          { dir: "apps/storybook", token: "CHROMATIC_PROJECT_TOKEN" },
          { dir: "apps/cyberstorm-storybook", token: "CHROMATIC_CYBERSTORM_TOKEN" },
        ]
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets[matrix.projects.token] }}
          workingDir: ${{ matrix.projects.dir }}
          exitOnceUploaded: true
