name: Test

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  get-node-version:
    name: Get Node version
    if: github.event_name != 'pull_request' || (github.event_name == 'pull_request' && github.event.base.repo.id != github.event.head.repo.id)
    runs-on: ubuntu-latest
    outputs:
      node-version: ${{ steps.get-node-version.outputs.node-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Check get-node-version version
        uses: ./.github/actions/get-node-version
        with:
          package-json: .github/actions/get-node-version/package.json
      - name: Get Node version
        id: get-node-version
        uses: ./.github/actions/get-node-version

  pre-commit:
    name: Code style check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install pre-commit
        run: curl https://pre-commit.com/install-local.py | python -
      - name: Run pre-commit
        run: ~/bin/pre-commit run --show-diff-on-failure --color=always --all-files

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: get-node-version
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node ${{ needs.get-node-version.outputs.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ needs.get-node-version.outputs.node-version }}
      - name: Get yarn cache directory path
        id: yarn-cache-path
        run: echo "::set-output name=path::$(yarn cache dir)"
      - name: Cache Yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-path.outputs.path }}
          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-${{ runner.os }}-
      - name: Install Yarn dependencies
        run: yarn install --frozen-lockfile
      - name: Build @thunderstore/hooks
        run: yarn workspace @thunderstore/hooks build
      - name: Build @thunderstore/components
        run: yarn workspace @thunderstore/components build
      - name: Build @thunderstore/nextjs
        run: yarn workspace @thunderstore/nextjs build
